//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asp_project1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Table
    {
        public int Id { get; set; }
        public string Team_A { get; set; }
        public string Team_B { get; set; }
        public int Team_A_Score { get; set; }
        public int Team_B_Score { get; set; }
    }
}
